### ISSUE TITLE
Get ibis query working

### ISSUE THREAD

**Issue by tiffanychu90** [CityOfLosAngeles/civis-gcp-transition#1]
@alexistome09 Can you look at this notebook: https://github.com/CityOfLosAngeles/civis-gcp-transition/blob/311-workflow/bigquery-credential.ipynb

I was able to correctly compile an ibis expression, but not to execute it. 

I'm using a `credentials.json` that I didn't check into the repo.

**Comment by tiffanychu90** [comment]
@alexistome09 I get this error when I try to execute the query (now that the `ibis` error is fixed: `PermissionDenied: 403 request failed: the user does not have 'bigquery.readsessions.create' permission for 'projects/ita-datalakepoc'`

**Comment by atome09** [comment]
@tiffanychu90, I added that access to the service account, can you please try again?

**Comment by tiffanychu90** [comment]
Also add the `bigquery.readsessions.getData` permission
