### ISSUE TITLE
Move active business script to GCP

### ISSUE THREAD

**Issue by tiffanychu90** [CityOfLosAngeles/civis-gcp-transition#9]
* Active business script pulls from Socrata, joins to census block groups, counts businesses per industry
* Writes to AGOL feature layer

- [x] Clean up script - update to newer `geopandas` syntax, opt for using dictionaries to map with updated values, rather than looping through each row and column.
- [x] Overwrite CSV in GitHub
- [x] Schedule in GCP

**Comment by tiffanychu90** [comment]
@trantom:  I added a `new_updated_table.parquet` into the `active-business` branch, the `src/` folder. `test4.ipynb` would probably be the relevant notebook.

**Comment by tiffanychu90** [comment]
@trantom: The solution is here! https://github.com/CityOfLosAngeles/civis-gcp-transition/blob/master/src/activebusiness_blockgroup.py#L204-L225

**Comment by tiffanychu90** [comment]
@alexistome09 or @angelarafiles-lacityorg: Can you help with setting up a Cloud Run for `src/activebusiness_blockgroup.py`?

**Comment by trantom** [comment]
@tiffanychu90 Thank you for letting me in on it and the discussion.  Definitely a little bit of tangle with the objects.  Good stuff! 👍

**Comment by alexistome09** [comment]
@tiffanychu90 I will work on this.
